// Code generated by "stringer -type=TokenType token.go"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidToken-0]
	_ = x[EOL-1]
	_ = x[EOF-2]
	_ = x[IntLit-3]
	_ = x[FloatLit-4]
	_ = x[Name-5]
	_ = x[Sticky-6]
	_ = x[NotSticky-7]
	_ = x[Call-8]
}

const _TokenType_name = "InvalidTokenEOLEOFIntLitFloatLitNameStickyNotStickyCall"

var _TokenType_index = [...]uint8{0, 12, 15, 18, 24, 32, 36, 42, 51, 55}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
