// Code generated by "stringer -type TokenType token.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InvalidToken-0]
	_ = x[IntLit-1]
	_ = x[FloatLit-2]
	_ = x[VarName-3]
	_ = x[Op-4]
	_ = x[Assign-5]
	_ = x[Paren-6]
}

const _TokenType_name = "InvalidTokenIntLitFloatLitVarNameOpAssignParen"

var _TokenType_index = [...]uint8{0, 12, 18, 26, 33, 35, 41, 46}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
